[DOC04] Definir metas de usabilidade
Interacao-Humano-Computador/2020.1-Zupper pull request #20
Opened 2020-10-14 19:15 UTC by MaiconMares

#17 O documento descreve as Metas de Usabilidade com clareza e indica quais são relevantes para o projeto e exemplos que justificam a escolha.

2020-10-14 23:05 UTC, jps12 commented on docs/metas-de-usabilidade.md
> +## Referências
Não tem referências aqui

2020-10-14 23:07 UTC, jps12 requested changes
No arquivo de metas de usabilidade não tem referências, vai colocar ou era versionamento?

2020-10-15 10:00 UTC, MaiconMares commented
> No arquivo de metas de usabilidade não tem referências, vai colocar ou era versionamento?

Esqueci de adicioná-las, será feito.

2020-10-15 14:41 UTC, jps12 approved these changes
Tudo está de acordo com o esperado. Pull request aceito

2020-10-15 14:41 UTC, merged