[DOC07] Expeirmento 1 de analise de tarefas
Interacao-Humano-Computador/2020.1-Zupper pull request #42
Opened 2020-11-12 10:54 UTC by RenatoBrittoAraujo

2020-11-12 11:06 UTC, MaiconMares requested changes
@RenatoBrittoAraujo não há relato dos resultados, nem sugestões de melhoria. Por favor, adicionar e linkar issue ao qual o PR está ligado.

2020-11-12 12:24 UTC, RenatoBrittoAraujo commented
Mudanças feitas. Relato dos resultados existe no documento já.

2020-11-12 12:50 UTC, MaiconMares commented
> Mudanças feitas. Relato dos resultados existe no documento já.

Dei uma olhada, porém sugerir como melhoria "avanços de usabilidade e minimalismo" não quer dizer nada, isto é algo muito generalista. Exemplo de melhoria: diminuir quantidade de informações na tela de compras, tornar a tarefa A mais simples, simplificar a tarefa A separando-a em tarefas A e B.

2020-11-15 18:00 UTC, MaiconMares approved these changes

2020-11-15 18:01 UTC, merged